esphome:
  name: sas
  platform: ESP8266
  board: esp_wroom_02

wifi:
  ssid: "buttersIOT"
  password: "das"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sas Fallback Hotspot"
    password: "qoKSKJoB6myn"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
